version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tg_bot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: tg_bot_app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:

