"""Первая миграция с alembic

Revision ID: d441707484f2
Revises: 
Create Date: 2026-01-26 12:23:48.135332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd441707484f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('gift_text', sa.Text(), nullable=True))
    op.add_column('transfers', sa.Column('gift_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'gift_url')
    op.drop_column('transfers', 'gift_text')
    # ### end Alembic commands ###
